version: 0.2

phases:
  install:
    commands:
      - echo install phase
  pre_build:
    commands:
      - echo pre_build phase
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew build
artifacts:
  files:
    - build/**/*
